// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjIVRl30B5wj4WQd4wbs7DiFzEjDIaQk',
    appId: '1:275026923983:web:93486f58f639600a3682ba',
    messagingSenderId: '275026923983',
    projectId: 'my-login-app-c8125',
    authDomain: 'my-login-app-c8125.firebaseapp.com',
    storageBucket: 'my-login-app-c8125.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjtvY9eDjZxjwTqdkbszJE_SVUTTnfd5E',
    appId: '1:275026923983:android:e42baab25715b68f3682ba',
    messagingSenderId: '275026923983',
    projectId: 'my-login-app-c8125',
    storageBucket: 'my-login-app-c8125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpsPsWMct-OJyvloSORfJmxPGpH6B0Ak',
    appId: '1:275026923983:ios:d28065d0f5ffdb573682ba',
    messagingSenderId: '275026923983',
    projectId: 'my-login-app-c8125',
    storageBucket: 'my-login-app-c8125.appspot.com',
    androidClientId: '275026923983-99n38oa1amcoc31hc1ut59q4ks4cpa6p.apps.googleusercontent.com',
    iosClientId: '275026923983-9p4lo2h4jsr6llg2pq8tl33upf9q3u87.apps.googleusercontent.com',
    iosBundleId: 'com.example.appioc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWpsPsWMct-OJyvloSORfJmxPGpH6B0Ak',
    appId: '1:275026923983:ios:4d1c1814f174cf453682ba',
    messagingSenderId: '275026923983',
    projectId: 'my-login-app-c8125',
    storageBucket: 'my-login-app-c8125.appspot.com',
    androidClientId: '275026923983-99n38oa1amcoc31hc1ut59q4ks4cpa6p.apps.googleusercontent.com',
    iosClientId: '275026923983-gf9g84ps6r7ckg8doudgfs2m9feqo4p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.appioc.RunnerTests',
  );
}
